// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr7CG32iPkpRGyetQAxy020LG9d3CFWZY',
    appId: '1:2941007798:web:72232a3e9f4bffa36cf317',
    messagingSenderId: '2941007798',
    projectId: 'lab08-102-c61ae',
    authDomain: 'lab08-102-c61ae.firebaseapp.com',
    storageBucket: 'lab08-102-c61ae.appspot.com',
    measurementId: 'G-M8EHJ3X8QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDroTAhrKKxgYfH4sXwa_jkg43-ofwC4YA',
    appId: '1:2941007798:android:1ba432796dfe9d596cf317',
    messagingSenderId: '2941007798',
    projectId: 'lab08-102-c61ae',
    storageBucket: 'lab08-102-c61ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHzxXMGuWIgc-2Zzp1roNR5bdTh9qyXg',
    appId: '1:2941007798:ios:41d491e3dfc13ce46cf317',
    messagingSenderId: '2941007798',
    projectId: 'lab08-102-c61ae',
    storageBucket: 'lab08-102-c61ae.appspot.com',
    iosClientId: '2941007798-d2ih4rnsea62j0jjlnbiqi76b92anhhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHzxXMGuWIgc-2Zzp1roNR5bdTh9qyXg',
    appId: '1:2941007798:ios:41d491e3dfc13ce46cf317',
    messagingSenderId: '2941007798',
    projectId: 'lab08-102-c61ae',
    storageBucket: 'lab08-102-c61ae.appspot.com',
    iosClientId: '2941007798-d2ih4rnsea62j0jjlnbiqi76b92anhhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab9',
  );
}
